"""first init db

Revision ID: 96b2a795686f
Revises: ff76c999f36f
Create Date: 2018-05-25 10:24:32.230026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b2a795686f'
down_revision = 'ff76c999f36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'book', ['title'], unique=True)
    # ### end Alembic commands ###
